#Allows messages to be sent e.g. from ResponseStatusException
server:
  port: 8080
  error:
    include-message: always

spring:
  banner:
    image:
      location: classpath:/user-service/src/main/resources/banner.txt

  jpa:
    open-in-view: true

    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings:

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

